apiVersion: v1                  # <-- should be v1 for Service
kind: Service
metadata:
  name: todoui-service
  namespace: tod-ns
spec:
  selector:
    app: microtodoui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
